version: '3.8'

services:
  # Load Balancer / API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - SEARCH_SERVICE_URLS=http://search-service-1:8001,http://search-service-2:8002,http://search-service-3:8003
      - TYPEAHEAD_SERVICE_URLS=http://typeahead-service-1:8011,http://typeahead-service-2:8012
      - INDEXING_SERVICE_URLS=http://indexing-service-1:8021,http://indexing-service-2:8022,http://indexing-service-3:8023
    depends_on:
      - redis
      - search-service-1
      - search-service-2
      - search-service-3
      - typeahead-service-1
      - typeahead-service-2
    networks:
      - search-network

  # Search Services (Sharded)
  search-service-1:
    build: ./services/search-service
    ports:
      - "8001:8001"
    environment:
      - SERVICE_PORT=8001
      - SHARD_ID=0
      - TOTAL_SHARDS=3
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - INDEX_PATH=/data/indexes/shard-0
    volumes:
      - ./data/indexes/shard-0:/data/indexes/shard-0
    depends_on:
      - redis
      - postgres
    networks:
      - search-network

  search-service-2:
    build: ./services/search-service
    ports:
      - "8002:8002"
    environment:
      - SERVICE_PORT=8002
      - SHARD_ID=1
      - TOTAL_SHARDS=3
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - INDEX_PATH=/data/indexes/shard-1
    volumes:
      - ./data/indexes/shard-1:/data/indexes/shard-1
    depends_on:
      - redis
      - postgres
    networks:
      - search-network

  search-service-3:
    build: ./services/search-service
    ports:
      - "8003:8003"
    environment:
      - SERVICE_PORT=8003
      - SHARD_ID=2
      - TOTAL_SHARDS=3
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - INDEX_PATH=/data/indexes/shard-2
    volumes:
      - ./data/indexes/shard-2:/data/indexes/shard-2
    depends_on:
      - redis
      - postgres
    networks:
      - search-network

  # Typeahead Services (Sharded)
  typeahead-service-1:
    build: ./services/typeahead-service
    ports:
      - "8011:8011"
    environment:
      - SERVICE_PORT=8011
      - SHARD_ID=0
      - TOTAL_SHARDS=2
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - TRIE_PATH=/data/tries/shard-0
    volumes:
      - ./data/tries/shard-0:/data/tries/shard-0
    depends_on:
      - redis
      - postgres
    networks:
      - search-network

  typeahead-service-2:
    build: ./services/typeahead-service
    ports:
      - "8012:8012"
    environment:
      - SERVICE_PORT=8012
      - SHARD_ID=1
      - TOTAL_SHARDS=2
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - TRIE_PATH=/data/tries/shard-1
    volumes:
      - ./data/tries/shard-1:/data/tries/shard-1
    depends_on:
      - redis
      - postgres
    networks:
      - search-network

  # Indexing Services (Sharded)
  indexing-service-1:
    build: ./services/indexing-service
    ports:
      - "8021:8021"
    environment:
      - SERVICE_PORT=8021
      - SHARD_ID=0
      - TOTAL_SHARDS=3
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - INDEX_PATH=/data/indexes/shard-0
      - KAFKA_BROKERS=kafka:9092
    volumes:
      - ./data/indexes/shard-0:/data/indexes/shard-0
    depends_on:
      - redis
      - postgres
      - kafka
    networks:
      - search-network

  indexing-service-2:
    build: ./services/indexing-service
    ports:
      - "8022:8022"
    environment:
      - SERVICE_PORT=8022
      - SHARD_ID=1
      - TOTAL_SHARDS=3
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - INDEX_PATH=/data/indexes/shard-1
      - KAFKA_BROKERS=kafka:9092
    volumes:
      - ./data/indexes/shard-1:/data/indexes/shard-1
    depends_on:
      - redis
      - postgres
      - kafka
    networks:
      - search-network

  indexing-service-3:
    build: ./services/indexing-service
    ports:
      - "8023:8023"
    environment:
      - SERVICE_PORT=8023
      - SHARD_ID=2
      - TOTAL_SHARDS=3
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/searchdb
      - INDEX_PATH=/data/indexes/shard-2
      - KAFKA_BROKERS=kafka:9092
    volumes:
      - ./data/indexes/shard-2:/data/indexes/shard-2
    depends_on:
      - redis
      - postgres
      - kafka
    networks:
      - search-network

  # Data Ingestion Service
  data-ingestion:
    build: ./services/data-ingestion
    ports:
      - "8030:8030"
    environment:
      - SERVICE_PORT=8030
      - KAFKA_BROKERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis
    networks:
      - search-network

  # Infrastructure Services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - search-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=searchdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - search-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - search-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - search-network

volumes:
  redis-data:
  postgres-data:

networks:
  search-network:
    driver: bridge 